### ISSUE TITLE
Library has no strong name

### ISSUE THREAD

**Issue by quorse** [Jinjinov/Hardware.Info#17]
Is any way to sign the assembly with public sign

**Comment by Jinjinov** [comment]
Strong naming is not recommended anymore by Microsoft:

https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md#1-microsoft-strong-names-their-assemblies-should-i

You can still do it yourself if you use one of these NuGet packages:

https://github.com/dsplaisted/strongnamer

https://github.com/brutaldev/StrongNameSigner

**Comment by timoria21** [comment]
This is ridiculous, I've used thousands of NuGet packages and this is the only not signed one. Even if Microsoft does not recommend this anymore it's a de facto industry standard. Please reconsider this decision.

**Comment by Jinjinov** [comment]
Dear sir!

Please be respectful here!

If I have taken the time to find the exact article where Microsoft explains why it is NOT needed:

> For the most part, the majority of applications do not need strong-names. Strong-names are left over from previous eras of .NET where [sandboxing](https://en.wikipedia.org/wiki/Sandbox_(computer_security)) needed to differentiate between code that was trusted, versus code that was untrusted. However in recent years, sandboxing via AppDomains, especially to [isolate ASP.NET web applications](https://support.microsoft.com/en-us/help/2698981/asp-net-partial-trust-does-not-guarantee-application-isolation), is no longer guaranteed and is not recommended.

then you can take the time to ACTUALLY read the provided link:
 
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md#1-microsoft-strong-names-their-assemblies-should-i

Your unsupported claims have no place here!

**Comment by timoria21** [comment]
Yes, I actually read the provided link:

> Because of the viral nature of strong-naming, **it is recommended that publicly published .NET libraries are strong-named**. Not strong-naming a .NET library excludes anyone who does need to strong-name their application or library from using it. Read more about .NET libraries and strong-naming in the [.NET Library Guidance](https://docs.microsoft.com/dotnet/standard/library-guidance/strong-naming).

**Comment by Jinjinov** [comment]
Ok, I think we can agree that Microsoft could be more clear about this, because you can see here: https://learn.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name

> Although .NET Core supports strong-named assemblies, and all assemblies in the .NET Core library are signed, the majority of third-party assemblies do not need strong names.

The main reason why this library is not strong named is because it is a .NET Standard 2.0 library that is compatible with both .NET Framework and .NET Core and I wanted to avoid problems that come with strict assembly loading in .NET Framework:

https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming

> When .NET developers complain about strong naming, what they're usually complaining about is strict assembly loading. Fortunately, this issue is isolated to .NET Framework. .NET 5+, .NET Core, Xamarin, UWP, and most other .NET implementations don't have strict assembly loading, which is the main downside of strong naming.

and other problems:

> There are three major problems that developers run into after strong naming their assemblies:

https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md#2-i-really-really-need-to-strong-name-what-kinds-of-issues-will-i-run-into

From the 285.000 downloads of this NuGet from https://www.nuget.org/packages/Hardware.Info there were 2 complaints about strong naming, so I am guessing that this issue is not critical for the vast majority of people who use it.

**Comment by timoria21** [comment]
In my .NET Framework software component, I use 20 (strong-named) NuGet packages and I cannot use `Hardware.Info` because is not strong-named. Using a **StrongNamer** means (for my customers) having an additional package around that has nothing to do with the core business of the software component, something that (as a customer) you don't know if you need to redistribute or not with your app.

In the .NET Framework era, all assemblies were signed, and even if today Microsoft changed its mind, we cannot avoid it.

I'm one of the 285.000 downloaders who will discard your package because it is not strong-named. The only difference is that I took the time to discuss this topic with you.

**Comment by ilCosmico** [comment]
Hi @Jinjinov, 

I am also interested in a signed version of the package for .Net Framework.
Why not just include it in the same NuGet package?

I mean something like done from this library
![image](https://github.com/Jinjinov/Hardware.Info/assets/8678145/9d9a3552-991b-4d16-9581-c6e5cac56c1f)

**Comment by Jinjinov** [comment]
We have two Microsoft articles saying that strong naming is not necessary:

> For the most part, the majority of applications do not need strong-names. Strong-names are left over from previous eras of .NET where [sandboxing](https://en.wikipedia.org/wiki/Sandbox_(computer_security)) needed to differentiate between code that was trusted, versus code that was untrusted. However in recent years, sandboxing via AppDomains, especially to [isolate ASP.NET web applications](https://support.microsoft.com/en-us/help/2698981/asp-net-partial-trust-does-not-guarantee-application-isolation), is no longer guaranteed and is not recommended.

> Although .NET Core supports strong-named assemblies, and all assemblies in the .NET Core library are signed, the majority of third-party assemblies do not need strong names.

And we have two Microsoft articles saying that strong naming is necessary:

> Because of the viral nature of strong-naming, it is recommended that publicly published .NET libraries are strong-named. Not strong-naming a .NET library excludes anyone who does need to strong-name their application or library from using it. Read more about .NET libraries and strong-naming in the [.NET Library Guidance](https://docs.microsoft.com/dotnet/standard/library-guidance/strong-naming).

> This guidance is specific to publicly distributed .NET libraries, such as .NET libraries published on NuGet.org. Strong naming is not required by most .NET applications and should not be done by default.

In the end I have decided to use strong naming. I will reopen this issue and make a new version of the NuGet package.

**Comment by ilCosmico** [comment]
Any ETA for the new version with strong naming?
