### ISSUE TITLE
Use in Raspberry Pi 

### ISSUE THREAD

**Issue by gkapellmann** [Jinjinov/Hardware.Info#25]
I have tried to get this nuget package in a Raspberry Pi 4, but it always fails. 

I do it using: dotnet add package Hardware.Info

I was wondering if this should work? Or if it has been tested in a Raspberry Pi device?

**Comment by Jinjinov** [comment]
there is a very good reason for the New issue template - you have to fill it out, so I can help you - because I can't read your mind and I can't fix anything if I don't know what doesn't work

what version of the package?

what operating system?

what fails?

what are the precise and detailed steps to reproduce this failure?
