### ISSUE TITLE
Network speed is set to 0 or set to long.MaxValue in certain circumstances

### ISSUE THREAD

**Issue by isenmann** [Jinjinov/Hardware.Info#43]
### Library version
11.0.1.1
### OS & OS version
Windows 11
### Describe the bug
There are two scenarios when the network speed is displayed incorrect:

1. If no network cable is plugged in, the network speed is set to long.MaxValue. Better would be 0 which can be read in the Win32_PerfFormattedData_Tcpip_NetworkAdapter
2. If there is no Speed value at all in Win32_NetworkAdapter, the value is set to default of long which is 0. But the correct value is available in Win32_PerfFormattedData_Tcpip_NetworkAdapter

As you can see the network speed is set to long.MaxValue because the network card isn't plugged in at all, which you can see in the NetConnectionStatus is set to 7
![SpeedMax](https://github.com/Jinjinov/Hardware.Info/assets/1726665/8fb1cb91-19b0-4247-ae3e-f7e448d948fc)

And in this network adapter there is no speed at all which leads to a value of 0 because GetPropertyValue returns the default. But if you read the network speed from Win32_PerfFormattedData_Tcpip_NetworkAdapter the value is set correctly there, so as fallback you could read that value.
![SpeedNotAvailable](https://github.com/Jinjinov/Hardware.Info/assets/1726665/2d011f95-4dd0-47b7-bf4c-210882106459)

### Expected behavior
The network speed should displayed correctly and shoudl not be misleading

**Comment by Jinjinov** [comment]
Thank you for noticing the problem.

Your solution would be perfect, if this issue didn't exist:

https://github.com/Jinjinov/Hardware.Info#21-second-delay-on-first-use-in-windows

Unfortunately, accessing `Win32_PerfFormattedData_Tcpip_NetworkAdapter` causes this issue, that is why I made the `bool` option to skip reading this data for people who can't have that delay in their program.

https://github.com/Jinjinov/Hardware.Info#refresh-methods-settings

I can't think of a way that would read `CurrentBandwidth` from `Win32_PerfFormattedData_Tcpip_NetworkAdapter` when `includeBytesPersec` is false and not cause the delay.

The only thing I can think of is adjusting your fix so that it executes only if `includeBytesPersec` is true, and adding the `networkAdapter.Speed` problem to the Readme file under Known issues. That way, people can still opt in for `includeBytesPersec` and have the `networkAdapter.Speed` problem fix, but people who can't tolerate the delay will still have their code run fast.

**Comment by isenmann** [comment]
I'm fine with your suggestion and I can understand it. 

I will change my pull request to fix it only if `includeBytesPersec` is true.

**Comment by isenmann** [comment]
Pull request changed as mentioned above, only if `includeBytesPersec` is set to true and the Speed maybe wrong, the speed will be read from the `CurrentBandwidth` property

**Comment by Jinjinov** [comment]
Thank you!

I am thinking of renaming `includeBytesPersec` to `includeDataFrom_Win32_PerfFormattedData_Tcpip_NetworkAdapter_ThatCauses21SecondDelayTheFirstTimeAfterWindowsRestart` - do you have a better idea? :)

One more thing - in `Win32_NetworkAdapter` the `Speed` is `uint64` - and I see in your code that you compare to `networkAdapter.Speed == long.MaxValue` and not `networkAdapter.Speed == ulong.MaxValue` - is this correct? (I didn't check it myself)

**Comment by isenmann** [comment]
> I am thinking of renaming `includeBytesPersec` to `includeDataFrom_Win32_PerfFormattedData_Tcpip_NetworkAdapter_ThatCauses21SecondDelayTheFirstTimeAfterWindowsRestart` - do you have a better idea? :)

Not really, maybe something like `includeMoreDataButWithDelay` or something like that. :)

> One more thing - in `Win32_NetworkAdapter` the `Speed` is `uint64` - and I see in your code that you compare to `networkAdapter.Speed == long.MaxValue` and not `networkAdapter.Speed == ulong.MaxValue` - is this correct? (I didn't check it myself)

That's correct. The value is long.MaxValue and never ulong.MaxValue. I don't know why they use a ulong here, but it's definitely a long.maxValue for speed.

**Comment by Jinjinov** [comment]
Fixed in https://github.com/Jinjinov/Hardware.Info/releases/tag/v11.1.0.0

I couldn't think of a better name for `includeBytesPersec`, because the same parameter is used in macOS and Linux. It is a bit misleading now that it includes `CurrentBandwidth`.

I explained it in https://github.com/Jinjinov/Hardware.Info#invalid-networkadapterspeed-in-windows
