### ISSUE TITLE
Network interfaces cannot be refreshed when the available address families are restricted with systemd

### ISSUE THREAD

**Issue by Nihlus** [Jinjinov/Hardware.Info#46]
### Library version
11.1.0

### OS & OS version
Ubuntu 20.04
systemd 245

### Describe the bug
When attempting to refresh and query network devices while running as a systemd service with the hardening option `RestrictAddressFamilies` set to `AF_INET AF_INET6`, the library fails to enumerate the available interfaces with an exception. 

Removing this option resolves the issue.

### To Reproduce
1. Compile the program below.
2. Run the program as a systemd service with `RestrictAddressFamilies` set to `AF_INET AF_INET6`

```cs
using Hardware.Info;

var hardwareInfo = new HardwareInfo();
hardwareInfo.RefreshAll();
```

### Exceptions (if any)
```
Jun 10 11:35:36 Remora.Neos.Headless[649931]: Unhandled exception. System.Net.NetworkInformation.NetworkInformationException (0x80004005): Success
Jun 10 11:35:36 Remora.Neos.Headless[649931]:    at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
Jun 10 11:35:36 Remora.Neos.Headless[649931]:    at Hardware.Info.HardwareInfoBase.GetNetworkAdapterList(Boolean includeBytesPersec, Boolean includeNetworkAdapterConfiguration)
Jun 10 11:35:36 Remora.Neos.Headless[649931]:    at Hardware.Info.Linux.HardwareInfoRetrieval.GetNetworkAdapterList(Boolean includeBytesPersec, Boolean includeNetworkAdapterConfiguration)
Jun 10 11:35:36 Remora.Neos.Headless[649931]:    at Hardware.Info.HardwareInfo.RefreshNetworkAdapterList(Boolean includeBytesPerSec, Boolean includeNetworkAdapterConfiguration)
Jun 10 11:35:36 Remora.Neos.Headless[649931]:    at Hardware.Info.HardwareInfo.RefreshAll()
Jun 10 11:35:36 Remora.Neos.Headless[649931]:    at Program.<Main>$(String[] args)
Jun 10 11:35:36 Remora.Neos.Headless[649931]:    at Program.<Main>(String[] args)
```

### Expected behavior
Network interfaces should be successfully enumerated.

**Comment by Jinjinov** [comment]
This is the `Hardware.Info.HardwareInfoBase.GetNetworkAdapterList`

https://github.com/Jinjinov/Hardware.Info/blob/master/Hardware.Info/HardwareInfoBase.cs#L113

It is called here:

https://github.com/Jinjinov/Hardware.Info/blob/master/Hardware.Info/Linux/HardwareInfoRetrieval.cs#L642

I am not a Linux expert, I had to google what `systemd` means and I don't know how to make a `systemd service` or how to set `RestrictAddressFamilies` to `AF_INET AF_INET6`

I can't find the source code for `System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces`

There are a few issues on GitHub if you search "LinuxNetworkInterface" "GetLinuxNetworkInterfaces" "NetworkInformationException" but no results if you add "RestrictAddressFamilies"

I don't know how to solve this `System.Net.NetworkInformation.NetworkInformationException`

**Comment by Jinjinov** [comment]
This is from ChatGPT:

The System.Net.NetworkInformation.NetworkInformationException you are experiencing when running your program as a systemd service with RestrictAddressFamilies set to AF_INET and AF_INET6 is likely due to a restriction imposed by systemd.

When you set RestrictAddressFamilies in systemd, it limits the address families that the service can access. In this case, AF_INET and AF_INET6 restrict the service to only have access to IPv4 and IPv6 address families, respectively. This restriction can prevent the System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces() method from gathering the necessary network information and result in the exception.

To resolve this issue, you have a few options:

Adjust RestrictAddressFamilies: If your program requires access to network interfaces beyond just IPv4 and IPv6, you can modify the RestrictAddressFamilies setting in your systemd service unit file to include additional address families that your program needs, such as AF_PACKET for packet socket access. However, keep in mind that modifying this setting might introduce security risks, so carefully consider the implications before making any changes.

Use an alternative method: Instead of relying on the System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces() method, you can explore other approaches to retrieve network interface information. For example, you could use command-line utilities like ifconfig or ip and parse their output to gather the required data.

Adjust systemd configuration: If the restrictions imposed by systemd are not necessary for your use case, you could consider modifying the systemd configuration to remove or loosen the RestrictAddressFamilies setting for your service. However, be cautious with this option, as it may have broader security implications.

It's worth noting that the exact steps and configuration changes required may vary depending on your specific Linux distribution and systemd version. Consult the systemd documentation and your distribution's documentation for more information on configuring RestrictAddressFamilies and managing network interfaces in the context of systemd services.

**Comment by Jinjinov** [comment]
I would suggest that you use this solution suggested by ChatGPT:

```
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.NetworkInformation;

public List<NetworkInterface> GetNetworkInterfaces()
{
    var networkInterfaces = new List<NetworkInterface>();

    // Enumerate network interface files
    var interfaceFiles = Directory.EnumerateDirectories("/sys/class/net");

    foreach (var interfaceFile in interfaceFiles)
    {
        var interfaceName = Path.GetFileName(interfaceFile);

        // Read necessary information from files
        var macAddressFile = $"/sys/class/net/{interfaceName}/address";
        var ipFile = $"/proc/net/dev"; // You may need to parse this file differently based on your distribution

        var macAddress = File.ReadAllText(macAddressFile).Trim();
        var ipAddressInfo = File.ReadLines(ipFile)
            .FirstOrDefault(line => line.Contains(interfaceName))
            ?.Split(':')
            .LastOrDefault()
            ?.Trim();

        var ipAddress = // Parse IP address from ipAddressInfo
        var subnetMask = // Parse subnet mask from ipAddressInfo

        // Create NetworkInterface object
        var networkInterface = new NetworkInterface
        {
            Name = interfaceName,
            Description = interfaceName,
            Id = interfaceName,
            NetworkInterfaceType = NetworkInterfaceType.Ethernet,
            OperationalStatus = OperationalStatus.Up,
            GetPhysicalAddress = () => PhysicalAddress.Parse(macAddress),
        };

        networkInterface
            .GetIPProperties()
            .UnicastAddresses
            .Add(new UnicastIPAddressInformation(IPAddress.Parse(ipAddress), subnetMask));

        networkInterfaces.Add(networkInterface);
    }

    return networkInterfaces;
}
```

**Comment by Jinjinov** [comment]
This is another solution from ChatGPT:

```
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.NetworkInformation;

public class NetworkInterfaceInfo
{
    public string Name { get; set; }
    public string MacAddress { get; set; }
    public string IPAddress { get; set; }
    public string SubnetMask { get; set; }
}

public class NetworkInterfaceParser
{
    public List<NetworkInterfaceInfo> GetNetworkInterfaces()
    {
        var networkInterfaces = new List<NetworkInterfaceInfo>();

        var interfaceFiles = Directory.EnumerateDirectories("/sys/class/net");

        foreach (var interfaceFile in interfaceFiles)
        {
            var interfaceName = Path.GetFileName(interfaceFile);
            var interfaceInfo = ReadInterfaceInformation(interfaceName);

            if (interfaceInfo != null)
                networkInterfaces.Add(interfaceInfo);
        }

        return networkInterfaces;
    }

    private NetworkInterfaceInfo ReadInterfaceInformation(string interfaceName)
    {
        var interfaceInfo = new NetworkInterfaceInfo { Name = interfaceName };

        try
        {
            var macAddressFile = $"/sys/class/net/{interfaceName}/address";
            var ipFile = "/proc/net/dev";

            interfaceInfo.MacAddress = File.ReadAllText(macAddressFile).Trim();

            var ipAddressInfo = File.ReadLines(ipFile)
                .FirstOrDefault(line => line.Contains(interfaceName));

            if (ipAddressInfo != null)
            {
                var parts = ipAddressInfo.Split(':');
                var addresses = parts[1].Split(' ', StringSplitOptions.RemoveEmptyEntries);
                interfaceInfo.IPAddress = addresses[0];
                interfaceInfo.SubnetMask = addresses[1];
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error reading interface information for {interfaceName}: {ex.Message}");
            return null;
        }

        return interfaceInfo;
    }
}

public class Program
{
    public static void Main()
    {
        var networkInterfaceParser = new NetworkInterfaceParser();
        var networkInterfaces = networkInterfaceParser.GetNetworkInterfaces();

        Console.WriteLine("Network Interfaces:");
        foreach (var networkInterface in networkInterfaces)
        {
            Console.WriteLine($"Name: {networkInterface.Name}");
            Console.WriteLine($"MAC Address: {networkInterface.MacAddress}");
            Console.WriteLine($"IP Address: {networkInterface.IPAddress}");
            Console.WriteLine($"Subnet Mask: {networkInterface.SubnetMask}");
            Console.WriteLine();
        }
    }
}
```

**Comment by Nihlus** [comment]
I don't see how code suggestions from a chatbot are relevant to me. This is a bug report regarding functionality in this library, not a support request for how to enumerate network interfaces. Perhaps you'd be more helped by reading the suggestions yourself and utilizing the information when fixing the problem?

**Comment by Jinjinov** [comment]
I said that I am not a Linux expert and that I don't know how to make a systemd service or how to set RestrictAddressFamilies to AF_INET AF_INET6.

I was trying to brainstorm ideas with you. I spent the whole day thinking how I could incorporate this into the library.

I was expecting you to offer some help. It seems to me like you are not interested in doing that.

**Comment by Nihlus** [comment]
I'm happy to show you how to set up a systemd service if you've got a Linux VM to test things on. I apologize for my short tone; I was frustrated with having ChatGPT show up as the first reply.

**Comment by Jinjinov** [comment]
This was my first reply:

> This is the Hardware.Info.HardwareInfoBase.GetNetworkAdapterList
> 
> https://github.com/Jinjinov/Hardware.Info/blob/master/Hardware.Info/HardwareInfoBase.cs#L113
> 
> It is called here:
> 
> https://github.com/Jinjinov/Hardware.Info/blob/master/Hardware.Info/Linux/HardwareInfoRetrieval.cs#L642
> 
> I am not a Linux expert, I had to google what systemd means and I don't know how to make a systemd service or how to set RestrictAddressFamilies to AF_INET AF_INET6
> 
> I can't find the source code for System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces
> 
> There are a few issues on GitHub if you search "LinuxNetworkInterface" "GetLinuxNetworkInterfaces" "NetworkInformationException" but no results if you add "RestrictAddressFamilies"
> 
> I don't know how to solve this System.Net.NetworkInformation.NetworkInformationException

As my search on GitHub and StackOverflow didn't yield results after one hour, I resorted to ChatGPT since without it I would be literally without any idea on how to proceed.

My current plan is to wrap `HardwareInfoBase.GetNetworkAdapterList` in a try catch block and in case of a `NetworkInformationException` fall back to the code suggested by ChatGPT.

It would be really helpful if you could pull the repo and test if it is working.  If it works, I will refactor it into smaller methods, get rid of unnecessary repetitions and try to get data for additional properties.

**Comment by Nihlus** [comment]
Sorry for the late reply, busy week at work. That fix sounds reasonable, though the fallback code suggested by ChatGPT is wrong and does not read the device information correctly. `/proc/net/dev` does not contain IP address information, just the names of the network interfaces. You can read more about the structure of `/sys/class/net` here and the files that might be of use to you: https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-net

The way to get IP address information on Linux is through a protocol called netlink with which you can query any and all network-related information. There's no C# wrapper for it anywhere I can find, however, so if you want to use it you may need to read up on the protocol and implement a basic wrapper yourself: https://docs.kernel.org/userspace-api/netlink/intro.html

As it is, though, I think you'd be fine skipping IP address enumeration altogether unless you deem it super important. You could also try parsing `/proc/net/route` and `/proc/net/fib_trie`, which contain routing information for each interface and a tree-like structure of assigned addresses, respectively (more on that here: https://vincent.bernat.ch/en/blog/2017-ipv4-route-lookup-linux).

**Comment by Nihlus** [comment]
The original exception originates from [this](https://source.dot.net/#System.Net.NetworkInformation/System/Net/NetworkInformation/LinuxNetworkInterface.cs,82) line in the .NET source code, which may also put the problem into a bit of context. The code `0x80004005` is typically associated with FileNotFound errors and their ilk, which could indicate that the underlying call to `SystemNative_GetNetworkInterfaces` has some assumption that fails with the hardening options available.

**Comment by Jinjinov** [comment]
Thank you for all the useful links, they should help a lot!

I have Ubuntu running in a VirtualBox and now I see that ChatGPT was hallucinating. I removed most of the code it suggested. I will try to find it on the documentation you suggested and on StackOverflow.

**Comment by Jinjinov** [comment]
I used `/proc/net/route` and `/proc/net/fib_trie` like you suggested, and I also used https://stackoverflow.com/questions/5281341/get-local-network-interface-addresses-using-only-proc

I think that `GetNetworkAdapterList` and `RefreshNetworkAdapterList` and `RefreshAll` should work now even if `NetworkInformationException` is thrown.

I tested the fallback and it works, but I didn't test the exception, because my `Hardware.Info.Test` is not a systemd service.

Can you test it with a systemd service?

**Comment by Jinjinov** [comment]
Fixed in https://github.com/Jinjinov/Hardware.Info/releases/tag/v11.1.0.1
