### ISSUE TITLE
About the timeout exception.

### ISSUE THREAD

**Issue by jcyuan** [Jinjinov/Hardware.Info#63]
Hi, i'm sorry for this issue report and it's actually not a bug nor feature request....
just i'm confused about the WMI timeout value.
if i initialize the class this way:
```c#
var hardwareInfo = new HardwareInfo(false, TimeSpan.FromSeconds(1));
```
it will work normally even if fianlly it takes 6seconds.
but if i initialize it with `TimeSpan.FromTicks(1)` it will fail to create `HardwareInfo` instance.
(if pass null for the `TimeSpan` argument it will also throw exception immediately, for this case i can understand it's an invalid argument or something like that)
anyway, why 1 second works and 1 tick not?
what is the proper shortest timeout to choose?
thanks so much!
or maybe we can make the instance creating alwasy success, but fail on `RefeshXXX` methods?

**Comment by Jinjinov** [comment]
`timeoutInWMI` sets the `Timeout` property of the `EnumerationOptions` in the `ManagementObjectSearcher` that executes each query. The default value is `EnumerationOptions.InfiniteTimeout`.

There are one or more queries for each hardware component, so there are more than 16 queries executed on `RefreshAll()`. Right now there are 23 queries, so that means if you use `FromMilliseconds(100)` then the max time for all queries will be 23 * 100 ms if you call `RefreshAll()`. Of course you can call only one of the `Refresh*()` methods, then there will be fewer queries and shorter total time.

If a query reaches the timeout it will throw a `System.Management.ManagementException` exception where `ErrorCode` will be `System.Management.ManagementStatus.Timedout`. If you set the `timeoutInWMI` then use a `try-catch` block like this:

        IHardwareInfo hardwareInfo;

        try
        {
            hardwareInfo = new HardwareInfo(timeoutInWMI: TimeSpan.FromMilliseconds(100));

            hardwareInfo.RefreshAll();
        }
        catch (ManagementException ex) when (ex.ErrorCode == ManagementStatus.Timedout)
        {
            Console.WriteLine(ex);
        }

If the timeout is too short, you will not get the result because the exception will be thrown.

`HardwareInfo` constructor calls `RefreshOperatingSystem` and that is why it failed when you used `TimeSpan.FromTicks(1)`
If you look at `System.TimeSpan` you will see that `NanosecondsPerTick = 100`, so a tick is equal to 100 nanoseconds.

You can run the benchmark to find out how long the queries take: 
https://github.com/Jinjinov/Hardware.Info/tree/master/Hardware.Info.Benchmark

But you have to know that setting the timeout to the value of the benchmark will not work, you can use the benchmark values as an approximate starting point. I tried various values and sometimes the constructor succeeded with `FromMicroseconds(10)` but most times with a much higher value, like `FromMilliseconds(100)`, but `RefreshCPUList` and `RefreshNetworkAdapterList` will still time out.

These are values from my benchmark:

|                     Method |          nano|     micro| milli|
|--------------------------- |--------------|----------|------|
|     RefreshOperatingSystem |             2|         1|     1|
|        RefreshMemoryStatus |           460|         1|     1|
|         RefreshBatteryList |     1,624,392|     1,624|     1|
|            RefreshBIOSList |     1,785,673|     1,785|     1|
|             RefreshCPUList | 1,964,995,539| 1,964,995| 1,964|
|           RefreshDriveList |    62,452,668|    62,452|    62|
|        RefreshKeyboardList |     4,303,528|     4,303|     4|
|          RefreshMemoryList |     1,926,931|     1,926|     1|
|         RefreshMonitorList |     3,884,362|     3,884|     3|
|     RefreshMotherboardList |     1,782,235|     1,782|     1|
|           RefreshMouseList |     4,700,086|     4,700|     4|
|  RefreshNetworkAdapterList |   945,004,493|   945,004|   945|
|         RefreshPrinterList |    48,126,103|    48,126|    48|
|     RefreshSoundDeviceList |     4,154,082|     4,154|     4|
| RefreshVideoControllerList |     8,784,372|     8,784|     8|

**Comment by jcyuan** [comment]
> 8

pretty cool! really appreciate it!
for my case i need CPU / Memory / Video controller would be enough.
so from the reference table the timeout would be 1964 + 8 + 1, so in total 2seconds would be fine i believe?

thanks so much again! @Jinjinov

**Comment by Jinjinov** [comment]
Yes, just use the maximum value, because the timeout is for one query.
Each `Refresh*` method executes one query (or more).
