### ISSUE TITLE
RefreshCPUList can throw a DivideByZeroException on Linux

### ISSUE THREAD

**Issue by inelisoni** [Jinjinov/Hardware.Info#72]
### Library version
100.0.1.1
### OS, version, architecture (32 bit / 64 bit)
Ubuntu 22.04.4 LTS (GNU/Linux 6.5.0-1025-gcp x86_64)
### Describe the bug
Sometimes one or several consecutive calls `RefreshCPUList(includePercentProcessorTime: true)` can throw a `System.DivideByZeroException` on Linux machines.
### To Reproduce
Unfortunately, there are no specific steps to reproduce the issue.
### Expected behavior
No exception.

**Comment by Jinjinov** [comment]
Thank you for reporting this!

Can you copy paste the whole call stack where the exception occurres?

Does the exception still occur if you set includePercentProcessorTime to false?

**Comment by inelisoni** [comment]
Hi!
```
System.DivideByZeroException: Attempted to divide by zero.  
   at Hardware.Info.Linux.HardwareInfoRetrieval.GetCpuPercentage(String cpuStatLast, String cpuStatNow)
   at Hardware.Info.Linux.HardwareInfoRetrieval.GetCpuUsage(List`1 processorList)
   at Hardware.Info.Linux.HardwareInfoRetrieval.GetCpuList(Boolean includePercentProcessorTime)
```

**Comment by inelisoni** [comment]
We always set the `includePercentProcessorTime` flag to `true`, as we need to monitor CPU usage.

**Comment by Jinjinov** [comment]
Thank you for the call stack, that helped a lot!

Fixed in https://github.com/Jinjinov/Hardware.Info/releases/tag/v101.0.0.0

The `DivideByZeroException` was happening because the delay of 500 milliseconds between two CPU measurements was too small in your case, so I also added a `int millisecondsDelayBetweenTwoMeasurements` parameter.

I fixed the `DivideByZeroException` but now you might get 0 instead of `DivideByZeroException`.

If you get too many 0 results, try setting `millisecondsDelayBetweenTwoMeasurements` to 1000.

Read about it here: https://github.com/Jinjinov/Hardware.Info?tab=readme-ov-file#refresh-methods-settings
